// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozwgyiaqgjosmazpxgdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96d2d5aWFxZ2pvc21henB4Z2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MzczNTgsImV4cCI6MjA5MDIxMzM1OH0.cO62dA6rkhsAoeImkSyDBVjs3QEzgUVjYXt6z4DqqWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});